#!/usr/bin/env python3
"""
Alkaid Self-Optimization System v2 — Optimizer
Creates GitHub PRs for IDENTITY.md prompt optimization.
Triggers when pending improvements >= threshold.
"""
import aiohttp
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)


class Optimizer:
    """Creates GitHub PRs for prompt optimization."""

    def __init__(self, github_token: str, github_repo: str, threshold: int = 5):
        self.token = github_token
        self.repo = github_repo
        self.threshold = threshold
        self.headers = {
            "Authorization": "Bearer %s" % github_token,
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    async def check_and_create_pr(self, pending_count: int, improvements_summary: str,
                                   identity_draft: str) -> Dict[str, Any]:
        """
        If pending improvements >= threshold, create a GitHub PR
        with the optimized IDENTITY.md.

        Args:
            pending_count: Number of pending improvements
            improvements_summary: Markdown summary of improvements
            identity_draft: New IDENTITY.md content

        Returns:
            PR info dict or None
        """
        if pending_count < self.threshold:
            return None

        # Create a branch, commit the file, create PR
        branch_name = "alkaid/prompt-optimize-%s" % __import__("time").strftime("%Y%m%d")
        title = "Alkaid Prompt Optimization (%d improvements)" % pending_count
        body = (
            "## Alkaid Self-Optimization — Prompt Update\n\n"
            "**Triggered by:** %d pending improvements reached threshold (%d)\n\n"
            "### Improvements Applied\n\n%s\n\n"
            "### Changes\n\n"
            "Updated `IDENTITY.md` based on learned patterns.\n\n"
            "---\n*Auto-generated by Alkaid Self-Optimization System*"
        ) % (pending_count, self.threshold, improvements_summary)

        # For now, create an Issue instead of PR (simpler, no branch management needed)
        # Full PR creation requires: create branch → commit file → create PR
        # We use Issue as the first step, can upgrade to PR later
        return await self._create_optimization_issue(title, body)

    async def _create_optimization_issue(self, title: str, body: str) -> Dict[str, Any]:
        """Create a GitHub Issue for prompt optimization review."""
        url = "https://api.github.com/repos/%s/issues" % self.repo
        payload = {
            "title": title,
            "body": body,
            "labels": ["agent:alkaid", "prompt-optimization"],
        }
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(url, headers=self.headers, json=payload) as resp:
                    if resp.status == 201:
                        data = await resp.json()
                        logger.info("Optimization Issue created: #%d", data["number"])
                        return {"number": data["number"], "url": data["html_url"]}
                    text = await resp.text()
                    logger.error("Issue create failed: %d %s", resp.status, text[:200])
                    return None
        except Exception as e:
            logger.error("Issue create error: %s", e)
            return None
